# Generated by Django 3.2.6 on 2021-08-25 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fornecedor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caneta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(blank=True, max_length=45)),
                ('cor', models.CharField(blank=True, max_length=45)),
                ('ponta', models.CharField(blank=True, max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_maquina', models.CharField(blank=True, max_length=45)),
                ('data_fabricação', models.DateTimeField()),
                ('quantidade', models.IntegerField()),
                ('caneta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caneta.caneta')),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fornecedor.fornecedor')),
            ],
        ),
        migrations.CreateModel(
            name='Relatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_falhas', models.IntegerField()),
                ('código', models.CharField(max_length=45)),
                ('Fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fornecedor.fornecedor')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caneta.lote')),
            ],
        ),
    ]
