# Generated by Django 3.2.6 on 2021-08-25 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caneta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lote',
            name='data_fabricação',
            field=models.DateField(),
        ),
    ]
