# Generated by Django 3.2.6 on 2021-08-25 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caneta', '0002_alter_lote_data_fabricação'),
    ]

    operations = [
        migrations.RenameField(
            model_name='relatorio',
            old_name='código',
            new_name='codigo',
        ),
        migrations.RemoveField(
            model_name='relatorio',
            name='Fornecedor',
        ),
    ]
